var randomInArray = require("./randomInArray");
var sex = require("./sex");
var sexes = require("./sexes");

module.exports = function(inputSex) {
  "use strict";

  // Equal number of male and female common first names
  var firstNames = {
    male: [
      "Anton",
      "August",
      "Alexander",
      "Andre",
      "Armin",
      "Benjamin",
      "Bernhard",
      "Burkhard",
      "Christoff",
      "Christian",
      "Christopher",
      "Daniel",
      "David",
      "Dominik",
      "Erik",
      "Emil",
      "Enrico",
      "Gabriel",
      "Gustav",
      "Isaac",
      "Ilias",
      "Josef",
      "Jan",
      "Jacob",
      "James",
      "Jens",
      "John",
      "Jonathan",
      "Jochen",
      "Joseph",
      "Joshua",
      "Julian",
      "Loan",
      "Liam",
      "Lennart",
      "Lucas",
      "Lukas",
      "Matthias",
      "Matthew",
      "Michael",
      "Norbert",
      "Nicholas",
      "Ortwin",
      "Robert",
      "Samuel",
      "Sven",
      "Tobias",
      "Thomas",
      "William",
      "Wolfgang"
    ],
    female: [
      "Anna",
      "Anne",
      "Ava",
      "Anneliese",
      "Antonia",
      "Alyssa",
      "Amalia",
      "Aurora",
      "Amelie",
      "Alexandra",
      "Audrey",
      "Amanda",
      "Anna-Lene",
      "Brigitte",
      "Berta",
      "Camila",
      "Charlotte",
      "Caroline",
      "Cordula",
      "Elizabeth",
      "Ella",
      "Emilie",
      "Emma",
      "Evelyn",
      "Gabriella",
      "Gertrud",
      "Hanna",
      "Hannah",
      "Isabella",
      "Karin",
      "Kerstin",
      "Layla",
      "Leah",
      "Lillian",
      "Lotte",
      "Laura",
      "Lena",
      "Magdalena",
      "Mia",
      "Natalie",
      "Nora",
      "Olivia",
      "Ruth",
      "Samantha",
      "Sarah",
      "Sonja",
      "Sofia",
      "Sophia",
      "Traudel",
      "Victoria",
      "Zoe",
      "Zoey"
    ]
  };

  inputSex = inputSex || sex();

  if (sexes.indexOf(inputSex) === -1) {
    throw new Error(inputSex + " is not a valid sex.");
  }

  return randomInArray(firstNames[inputSex]);
};
